//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlReplace.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UrlReplaceEnabled {
            get {
                return ((bool)(this["UrlReplaceEnabled"]));
            }
            set {
                this["UrlReplaceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UrlReplaceUIShown {
            get {
                return ((bool)(this["UrlReplaceUIShown"]));
            }
            set {
                this["UrlReplaceUIShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string DisplayMode {
            get {
                return ((string)(this["DisplayMode"]));
            }
            set {
                this["DisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:Group}")]
        public string GroupeMode {
            get {
                return ((string)(this["GroupeMode"]));
            }
            set {
                this["GroupeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <?xml version=""1.0"" encoding=""utf-8""?>
          <ArrayOfActionItem xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
          <ActionItem Seek=""www.fiddler.com"" Replace=""www.fiddler2.com"" Group=""Demo replaces"" Comment=""Demonstrates a simpel host only replace"" HostOnly=""true"" />
          <ActionItem Seek=""http://sandbox.fiddler2.com/"" Replace=""http://www.bayden.com/sandbox/"" Group=""Demo replaces"" Comment=""Demos a fill url replace"" />
          <ActionItem Seek=""help.fiddler2.com/(?&lt;parameter&gt;[^/]*)$"" Replace=""www.fiddler2.com/Fiddler/help/${parameter}.asp"" Group=""Demo replaces"" Comment=""Demos a simulated Url friendly help section"" IsRegEx=""true"" />
          </ArrayOfActionItem>
        ")]
        public string ActionItemsXml {
            get {
                return ((string)(this["ActionItemsXml"]));
            }
            set {
                this["ActionItemsXml"] = value;
            }
        }
    }
}
